import { StyleSheet } from "react-native";
import MainTheme from "./MainTheme";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContentList: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    marginTop: 50,
    justifyContent: "center",
    alignItems:"center",
    width: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalContentCreate: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    marginTop: 50,
    width: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalContentEdit: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    marginTop: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalContentRecipe: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    marginTop: 50,
    shadowColor: "#000",
    width: "90%",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    maxHeight: "70%",
  },
  header: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  subHeader: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 10,
  },
  paragraph: {
    fontSize: 14,
    marginBottom: 10,
  },
  closeButton: {
    padding: 10,
    backgroundColor: "#8a3633",
    borderRadius: 5,
    marginTop: 10,
  },
  closeButtonText: {
    fontSize: 16,
    color: "#ffffff",
    textAlign: "center",
  },
  editButton: {
    padding: 10,
    backgroundColor: "#FFA500",
    borderRadius: 5,
    marginTop: 10,
  },
  editButtonText: {
    fontSize: 16,
    color: "#ffffff",
    textAlign: "center",
  },
  saveButton: {
    padding: 10,
    backgroundColor: "#007BFF",
    borderRadius: 5,
    marginTop: 10,
  },
  saveButtonText: {
    fontSize: 16,
    color: "#ffffff",
    textAlign: "center",
  },
  circleButton: {
    backgroundColor: MainTheme.colors.highlightBlue,
    borderRadius: 25,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  circleButtonContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginHorizontal: 10,
    marginVertical: 10,
    gap: 24,
  },
  navButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 20,
  },
  tabButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: "#f0f0f0",
  },
  activeTab: {
    backgroundColor: "#007BFF",
  },
  tabText: {
    color: "#000",
    fontWeight: "bold",
  },
  searchInput: {
    borderWidth: 1,
    borderColor: "gray",
    padding: 10,
    borderRadius: 5,
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "gray",
    padding: 10,
    marginBottom: 10,
  },
  fullInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 10,
    borderRadius: 5,
    backgroundColor: "white",
  },
  ingredientRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8f8f8",
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
  },
  ingredientNameInput: {
    flex: 2,
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 8,
    borderRadius: 5,
    backgroundColor: "white",
  },
  quantityWrapper: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    justifyContent: "space-between",
    marginLeft: 10,
  },
  ingredientQuantityInput: {
    width: 50,
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 8,
    borderRadius: 5,
    backgroundColor: "white",
    textAlign: "center",
  },
  unitButton: {
    backgroundColor: "#007BFF",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 5,
    marginLeft: 5,
  },
  unitText: {
    color: "white",
    fontWeight: "bold",
  },
  recipeCard: {
    padding: 15,
    borderWidth: 3,
    borderColor: "#ccc",
    borderRadius: 5,
    marginBottom: 10,
  },
  recipeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  recipeName: {
    fontSize: 16,
    fontWeight: "bold",
  },
  emptyText: {
    textAlign: "center",
    marginTop: 20,
    fontSize: 16,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },

  recipeItem: {
    flexDirection: "row",
    borderWidth: 2,
    borderRadius: 8,
    borderColor: MainTheme.colors.dark20,
    paddingVertical: 8,
    paddingHorizontal: 24,
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: MainTheme.colors.textLight,
  },
  recipeList: {
    gap: 8,
    marginVertical: 16,
  },
  selectedRecipe: {
    flexDirection: "row",
    borderWidth: 2,
    borderRadius: 8,
    borderColor: MainTheme.colors.highlightBlue,
    paddingVertical: 8,
    paddingHorizontal: 24,
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: MainTheme.colors.blueMuted,
  }
  ,

  collectionHeader: {
    flexDirection: "row",
  },
  collectionItem: {
    paddingHorizontal: 8,
    borderRadius: 16,
    backgroundColor: MainTheme.colors.dark20,
  },
  collectionWrapper: {
    gap: 8,
  },

  menuOptions: {
    justifyContent: "center",
    alignItems: "center",
    padding: 8,
  }
});
